#ifndef KEYS_HPP
#define KEYS_HPP

#include <map>
#include <string>

namespace Blast2D{

    enum class Keys : unsigned int {
        Space = 32,
        Apostrophe = 39,
        Comma = 44,
        Minus = 45,
        Period = 46,
        Slash = 47,
        Num0 = 48,
        Num1 = 49,
        Num2 = 50,
        Num3 = 51,
        Num4 = 52,
        Num5 = 53,
        Num6 = 54,
        Num7 = 55,
        Num8 = 56,
        Num9 = 57,
        Semicolon = 59,
        Equal = 61,
        A = 65,
        B = 66,
        C = 67,
        D = 68,
        E = 69,
        F = 70,
        G = 71,
        H = 72,
        I = 73,
        J = 74,
        K = 75,
        L = 76,
        M = 77,
        N = 78,
        O = 79,
        P = 80,
        Q = 81,
        R = 82,
        S = 83,
        T = 84,
        U = 85,
        V = 86,
        W = 87,
        X = 88,
        Y = 89,
        Z = 90,
        LeftBracket = 91,
        Backslash = 92,
        RightBracket = 93,
        GraveAccent = 96,
        World1 = 161,
        World2 = 162,
        Escape = 256,
        Enter = 257,
        Tab = 258,
        Backspace = 259,
        Insert = 260,
        Delete = 261,
        Right = 262,
        Left = 263,
        Down = 264,
        Up = 265,
        PageUp = 266,
        PageDown = 267,
        Home = 268,
        End = 269,
        CapsLock = 280,
        ScrollLock = 281,
        NumLock = 282,
        PrintScreen = 283,
        Pause = 284,
        F1 = 290,
        F2 = 291,
        F3 = 292,
        F4 = 293,
        F5 = 294,
        F6 = 295,
        F7 = 296,
        F8 = 297,
        F9 = 298,
        F10 = 299,
        F11 = 300,
        F12 = 301,
        F13 = 302,
        F14 = 303,
        F15 = 304,
        F16 = 305,
        F17 = 306,
        F18 = 307,
        F19 = 308,
        F20 = 309,
        F21 = 310,
        F22 = 311,
        F23 = 312,
        F24 = 313,
        F25 = 314,
        KP0 = 320,
        KP1 = 321,
        KP2 = 322,
        KP3 = 323,
        KP4 = 324,
        KP5 = 325,
        KP6 = 326,
        KP7 = 327,
        KP8 = 328,
        KP9 = 329,
        KpDecimal = 330,
        KpDivide = 331,
        KpMultiply = 332,
        KpSubtract = 333,
        KpAdd = 334,
        KpEnter = 335,
        KpEqual = 336,
        LeftShift = 340,
        LeftControl = 341,
        LeftAlt = 342,
        LeftSuper = 343,
        RightShift = 344,
        RightControl = 345,
        RightAlt = 346,
        RightSuper = 347,
        Menu = 348
    };

    inline std::map<std::string, Keys> keys() {
        return {{"Space", Keys::Space},
                {"Apostrophe", Keys::Apostrophe},
                {"Comma", Keys::Comma},
                {"Minus", Keys::Minus},
                {"Period", Keys::Period},
                {"Slash", Keys::Slash},
                {"Num0", Keys::Num0},
                {"Num1", Keys::Num1},
                {"Num2", Keys::Num2},
                {"Num3", Keys::Num3},
                {"Num4", Keys::Num4},
                {"Num5", Keys::Num5},
                {"Num6", Keys::Num6},
                {"Num7", Keys::Num7},
                {"Num8", Keys::Num8},
                {"Num9", Keys::Num9},
                {"Semicolon", Keys::Semicolon},
                {"Equal", Keys::Equal},
                {"A", Keys::A},
                {"B", Keys::B},
                { "C", Keys::C },
                { "D", Keys::D },
                { "E", Keys::E },
                { "F", Keys::F },
                { "G", Keys::G },
                { "H", Keys::H },
                { "I", Keys::I },
                { "J", Keys::J },
                { "K", Keys::K },
                { "L", Keys::L },
                { "M", Keys::M },
                { "N", Keys::N },
                { "O", Keys::O },
                { "P", Keys::P },
                { "Q", Keys::Q },
                { "R", Keys::R },
                { "S", Keys::S },
                { "T", Keys::T },
                { "U", Keys::U },
                { "V", Keys::V },
                { "W", Keys::W },
                { "X", Keys::X },
                { "Y", Keys::Y },
                { "Z", Keys::Z},
                {"LeftBracket", Keys::LeftBracket},
                {"Backslash", Keys::Backslash},
                {"RightBracket", Keys::RightBracket},
                {"GraveAccent", Keys::GraveAccent},
                {"World1", Keys::World1},
                {"World2", Keys::World2},
                {"Escape", Keys::Escape},
                {"Enter", Keys::Enter},
                {"Tab", Keys::Tab},
                {"Backspace", Keys::Backspace},
                {"Insert", Keys::Insert},
                {"Delete", Keys::Delete},
                {"Right", Keys::Right},
                {"Left", Keys::Left},
                {"Down", Keys::Down},
                {"Up", Keys::Up},
                {"PageUp", Keys::PageUp},
                {"PageDown", Keys::PageDown},
                {"Home", Keys::Home},
                {"End", Keys::End},
                {"CapsLock", Keys::CapsLock},
                {"ScrollLock", Keys::ScrollLock},
                {"NumLock", Keys::NumLock},
                {"PrintScreen", Keys::PrintScreen},
                {"Pause", Keys::Pause},
                {"F1", Keys::F1},
                {"F2", Keys::F2},
                {"F3", Keys::F3},
                {"F4", Keys::F4},
                {"F5", Keys::F5},
                {"F6", Keys::F6},
                {"F7", Keys::F7},
                {"F8", Keys::F8},
                {"F9", Keys::F9},
                {"F10", Keys::F10},
                {"F11", Keys::F11},
                {"F12", Keys::F12},
                {"F13", Keys::F13},
                {"F14", Keys::F14},
                {"F15", Keys::F15},
                {"F16", Keys::F16},
                {"F17", Keys::F17},
                {"F18", Keys::F18},
                {"F19", Keys::F19},
                {"F20", Keys::F20},
                {"F21", Keys::F21},
                {"F22", Keys::F22},
                {"F23", Keys::F23},
                {"F24", Keys::F24},
                {"F25", Keys::F25},
                {"KP0", Keys::KP0},
                {"KP1", Keys::KP1},
                {"KP2", Keys::KP2},
                {"KP3", Keys::KP3},
                {"KP4", Keys::KP4},
                {"KP5", Keys::KP5},
                {"KP6", Keys::KP6},
                {"KP7", Keys::KP7},
                {"KP8", Keys::KP8},
                {"KP9", Keys::KP9},
                {"KpDecimal", Keys::KpDecimal},
                {"KpDivide", Keys::KpDivide},
                {"KpMultiply", Keys::KpMultiply},
                {"KpSubtract", Keys::KpSubtract},
                {"KpAdd", Keys::KpAdd},
                {"KpEnter", Keys::KpEnter},
                {"KpEqual", Keys::KpEqual},
                {"LeftShift", Keys::LeftShift},
                {"LeftControl", Keys::LeftControl},
                {"LeftAlt", Keys::LeftAlt},
                {"LeftSuper", Keys::LeftSuper},
                {"RightShift", Keys::RightShift},
                {"RightControl", Keys::RightControl},
                {"RightAlt", Keys::RightAlt},
                {"RightSuper", Keys::RightSuper},
                {"Menu", Keys::Menu}
        };
    }
}

#endif

